---
pagetitle: "Indicador de Condições Financeiras"
output: html_document
---

```{r setup, include = FALSE}
load("Dados/Informações para o relatório.RData")
```

### Juros - Brasil

```{r, warning = FALSE, message = FALSE, echo = FALSE}
juro_brasil
```

### Juros - Exterior

#### Curva de juros - 3 meses

```{r, warning = FALSE, message = FALSE, echo = FALSE}
juro_3m
```

#### Curva de juros - 2 anos

```{r, warning = FALSE, message = FALSE, echo = FALSE}
juro_2a
```

#### Curva de juros - 10 anos

```{r, warning = FALSE, message = FALSE, echo = FALSE}
juro_10a
```

### Commodities

```{r, warning = FALSE, message = FALSE, echo = FALSE}
commodities_plot
```

### Mercado de capitais

```{r, warning = FALSE, message = FALSE, echo = FALSE}
merc
```

### Moedas

```{r, warning = FALSE, message = FALSE, echo = FALSE}
moeda
```

### Petróleo

#### Gráfico unificado

```{r, warning = FALSE, message = FALSE, echo = FALSE}
wti_brent
```

#### Gráfico separado

```{r, warning = FALSE, message = FALSE, echo = FALSE}
petro_separado
```

### Risco

```{r, warning = FALSE, message = FALSE, echo = FALSE}
risk
```
